### PR TITLE
updated platforms notification types

### PR DESCRIPTION
**Pull request by wboereboom**
**Description**
The platforms notification types have been updated to the latest API specs and have been moved from the old way of exporting types to the new `Types` export in the library root.

**Fixed issue**:  #783

### CODE REVIEW

**Comment by wboereboom** [comment]
Note: There's a bug in the spec that causes an issue when trying to generate the `businessDetails` object. Currently investigating.

**Comment by wboereboom** [comment]
This PR can't be reviewed/merged yet due to a bug in the API spec that causes type generation issues. currently investigating

**Comment by wboereboom** [comment]
Problem solved, we can go ahead and merge this 🎉

**Review by maassenbas — APPROVED** [review]

**Review by zaiddreakh — APPROVED** [review]

**Comment by VincentvD** [comment]
Awesome! Thanks @wboereboom

**Comment by wboereboom** [comment]
You're welcome! The fix is part of release 10.1.0.

Happy coding!
Wouter
Adyen

**Pull request merged**
